apiVersion: v1
kind: Namespace
metadata:
  annotations:
    capability.openshift.io/name: openshift-samples+baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    workload.openshift.io/allowed: "management"
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-cluster-samples-operator
spec:
  finalizers:
  - kubernetes
