---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
