apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-samples-operator-imageconfig-reader
  annotations:
    capability.openshift.io/name: openshift-samples+baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - images
    verbs:
      - get
      - list
      - watch
