apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coreos-pull-secret-reader
  namespace: openshift-config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/single-node-production-edge: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator-openshift-config-secret-reader
  namespace: openshift-config
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/single-node-production-edge: "true"
subjects:
- kind: ServiceAccount
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
roleRef:
  kind: Role
  name: coreos-pull-secret-reader
  apiGroup: rbac.authorization.k8s.io
