kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
rules:
- apiGroups:
  - samplesoperator.config.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - "operatorstatus.openshift.io"
  resources:
  - clusteroperators
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator
rules:
- apiGroups:
  - samplesoperator.config.openshift.io
  resources:
  - "*"
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator
subjects:
- kind: ServiceAccount
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
roleRef:
  kind: Role
  name: cluster-samples-operator

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator
subjects:
- kind: ServiceAccount
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
roleRef:
  kind: ClusterRole
  name: cluster-samples-operator
